version: '3.0'
services:
  mongodb:
    container_name: infa-mongo
    image: mongo:4.0.4
    ports:
      - 27018:27017
    volumes:
      - infra_mongo_data:/infra-data/mongod

  sites-mongodb:
    container_name: sites-mongo
    image: mongo:4.0.4
    ports:
      - 27017:27017
    volumes:
      - sites_mongo_data:/sites-data/mongodb

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/postgresdb
    environment:
      POSTGRES_DB: challenger
      POSTGRES_PASSWORD: challenger
      POSTGRES_USER: challenger
      PGDATA: /data/postgresdb/pgdata

volumes:
  sites_mongo_data:
    driver: local

  infra_mongo_data:
    driver: local

  postgres_data:
    driver: local
