"build:docker-api-gateway": "docker build --build-arg host=http://chabox.ru -t api-gateway:0.0.1 -f ./Api/Dockerfile .",
"build:docker-sites-checker": "docker build -t sites-checker:0.0.1 -f ./SitesChecker/Dockerfile .",
"build:docker-parser": "docker build -t parser:0.0.1 -f ./Parser/Dockerfile .",
"tag:docker-api-gateway": "docker tag api-gateway:0.0.1 repo.treescale.com/seven-challenger/api-gateway:0.0.1",
"tag:docker-sites-checker": "docker tag sites-checker:0.0.1 repo.treescale.com/seven-challenger/sites-checker:0.0.1",
"tag:docker-parser": "docker tag parser:0.0.1 repo.treescale.com/seven-challenger/parser:0.0.1",
"publish:docker-api-gateway": "yarn tag:docker-api-gateway && docker push repo.treescale.com/seven-challenger/api-gateway:0.0.1",
"publish:docker-sites-checker": "yarn tag:docker-sites-checker && docker push repo.treescale.com/seven-challenger/sites-checker:0.0.1",
"publish:docker-parser": "yarn tag:docker-parser && docker push repo.treescale.com/seven-challenger/parser:0.0.1",
"run:docker-api-gateway": "docker run --name api-gateway -d api-gateway:0.0.1",
"run:docker-sites-checker": "docker run --name sites-checker -d sites-checker:0.0.1",
"run:docker-parser": "docker run --name parser -d parser:0.0.1",
"run:compose": "docker-compose -f docker-compose.dev.yml up --build"