name: CI+CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test
      run:
        yarn test

    - name: Lint
      run:
        yarn lint

    - name: Initilize docker
      run: |
        echo ${{ secrets.DOCKER_REG_PASSWORD }} | docker login repo.treescale.com -u ${{ secrets.DOCKER_REG_USER }} --password-stdin
    - name: Update docker images
      run: |
        yarn build:docker-api-gateway
        yarn build:docker-site-checker
        yarn build:docker-parser

    - name: Publish docker images
      run: |
        yarn publish:docker-api-gateway
        yarn publish:docker-site-checker
        yarn publish:docker-parser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          name: 7challenger/infra
          repository: 7challenger/infra
          ref: refs/heads/master
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install ansible
        run:
          sudo apt install ansible

      - name: Initiliaze-ssh
        uses: 7challenger/init-ssh-js@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          ssh_known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run Ansible playbook
        run:
          ansible-playbook ./ansible/chabox/deploy-playbook.yml -e "dockerUser=${{ secrets.DOCKER_REG_USER }} dockerPassword=${{ secrets.DOCKER_REG_PASSWORD }}" -i ./ansible/chabox/inventory.yml
