name: CI+CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install deps
      run: |
        cd parsers-services
        yarn --ignore-engines

    - name: Build
      run: |
        cd parsers-services
        yarn build

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: js-build
        path: parsers-services/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          name: 7challenger/infra
          repository: 7challenger/infra
          ref: refs/heads/master
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install ansible
        run:
          sudo apt install ansible

      - name: Initiliaze-ssh
        uses: 7challenger/init-ssh-js@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          ssh_known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: js-build

      - name: Run Ansible playbook
        run:
          ansible-playbook ./ansible/deploy-playbook.yml -i ./ansible/inventory.yml
