name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install deps
      run: |
        cd parsers-services
        yarn --ignore-engines

    - name: Build
      run: |
        cd parsers-services
        yarn build

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: js-build
        path: parsers-services/build
